# Generated by Django 3.2.15 on 2022-09-06 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MainCategory',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerName', models.CharField(max_length=20)),
                ('ofervalue', models.IntegerField()),
            ],
            options={
                'db_table': 'Offer',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobileNo', models.CharField(max_length=10)),
                ('Address', models.TextField(max_length=100)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategoryName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('mainCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.maincategory')),
            ],
            options={
                'db_table': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('SubCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.subcategory')),
                ('mainCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.maincategory')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
