# Generated by Django 3.2.15 on 2022-09-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_hotel_hotelimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotelImage',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
